version: '3'
services:

    auth:
        build:
            context: https://github.com/entu/auth.git
        container_name: auth
        restart: always
        environment:
            NODE_ENV: production
            PORT: 80
            COOKIE_DOMAIN: .entu.ee
            MONGODB:
            MOBILE_ID:
            GOOGLE_ID:
            GOOGLE_SECRET:
            FACEBOOK_ID:
            FACEBOOK_SECRET:
            TAAT_ENTRYPOINT:
            TAAT_ISSUER:
            TAAT_CERT:
            TAAT_PRIVATECERT:

    nginx:
        image: 'nginx:1.14'
        container_name: nginx
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /data/nginx/ssl/dhparams.pem:/etc/nginx/dhparams.pem:ro
            - /data/nginx/ssl/id.crt:/etc/nginx/id.crt:ro
            - /data/nginx/sites:/etc/nginx/conf.d:ro
            - /data/nginx/log:/var/log/nginx
            - /data/letsencrypt/certs/archive:/etc/nginx/letsencrypt/archive:ro
            - /data/letsencrypt/certs/live:/etc/nginx/letsencrypt/live:ro
            - /data/letsencrypt/static:/etc/nginx/letsencrypt/static:ro
        depends_on:
            - auth
